[package]
name = "spl-token-metadata"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = "0.9"
borsh-derive = "0.9"
thiserror = "1.0"
solana-program = {version = "0.1.4", path = "../../../bbachain/sdk/program"}
